apiVersion: v1
kind: ConfigMap
metadata:
  name: qcon-api-vault-agent-config
data:
  vault-agent-config.hcl: |
    # Comment this out if running as sidecar instead of initContainer
    exit_after_auth = true

    pid_file = "/home/vault/pidfile"

    auto_auth {
        method "kubernetes" {
            mount_path = "auth/kubernetes"
            config = {
                role = "kubeauthbot-qcon-api-prod"
            }
        }

        sink "file" {
            config = {
                path = "/home/vault/.vault-token"
            }
        }
    }

    template {
    destination = "/etc/secrets/.env"
    contents = <<EOT
    {{- with secret "apps/data/web-apps/qcon-api" }}
    ADMIN_USERNAME="{{ .Data.data.ADMIN_USERNAME }}"
    ADMIN_PASSWORD="{{ .Data.data.ADMIN_PASSWORD }}"
    API_HTTP_ADDR="{{ .Data.data.API_HTTP_ADDR }}"
    API_KEY="{{ .Data.data.API_KEY }}"
    DJANGO_SECRET_KEY="{{ .Data.data.DJANGO_SECRET_KEY }}"
    {{ end }}
    EOT
    }