apiVersion: apps/v1
kind: Deployment
metadata:
  name: qcon-api
  labels:
    app: qcon-api
    env: prod
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: qcon-api
          image: registry.dev.ltc.bcit.ca/web-apps/qcon/qcon-api:stable
          volumeMounts:
            - mountPath: /code/.secrets
              name: shared-data
              subPath: .secrets
      volumes:
        - configMap:
            items:
              - key: vault-agent-config.hcl
                path: vault-agent-config.hcl
            name: qcon-api-vault-agent-config
          name: config
        - emptyDir: {}
          name: shared-data
      initContainers:
        - args:
            - agent
            - -config=/etc/vault/vault-agent-config.hcl
            - -log-level=debug
          env:
            - name: VAULT_ADDR
              value: https://vault.ltc.bcit.ca:8200
          image: vault
          name: vault-agent
          volumeMounts:
            - mountPath: /etc/vault
              name: config
            - mountPath: /etc/secrets
              name: shared-data