name: ${APP_NAME:-infrastructure-documentation}

services:
  app:
    build:
      context: .
      target: build
      platforms:
        - linux/amd64
        - linux/arm64

    command: ["serve", "--dev-addr=0.0.0.0:8080", "--livereload"]

    environment:
      - APP_NAME=infrastructure-documentation
      - DEBUG=true
      - CI=false
      - SKIP_CDN=false

    volumes:
      - .:/app

    ports:
      - "8080:8080"
