name: ${APP_NAME:-infrastructure-documentation}
services:
  app:
    build:
      context: .
      target: build
      platforms:
        - linux/amd64
        - linux/arm64

    command: ["serve", "--dev-addr=0.0.0.0:8080", "--livereload", "-f", "mkdocs.local.yml"]

    environment:
      - DEBUG=true
      - CI=false
      - MKDOCS_CDN_ENABLED=0
      - DISABLE_PLAUSIBLE=1

    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "8080:8080"
