name: ${APP_NAME:-infrastructure-documentation}

services:
  app:
    build:
      context: .
      target: build
      platforms:
        - linux/amd64
        - linux/arm64

      args:
        STATIC_ROOT: ${STATIC_ROOT:-/public}

    command: ["serve", "--dev-addr=0.0.0.0:8080"]

    environment:
      - DEBUG=true
      - CI=false

    volumes:
      - .:/app

    ports:
      - "8080:8080"
