site_name: LTC Infrastructure Documentation
site_url: https://infrastructure-documentation.ltc.bcit.ca/

repo_name: infrastructure-documentation
repo_url: https://issues.ltc.bcit.ca/web-apps/infrastructure-documentation.git

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/brands/connectdevelop
    repo: fontawesome/brands/git-alt
  features:
    # - navigation.sections
    # - navigation.expand
    - navigation.indexes
    - navigation.tracking
    # - navigation.top
    # - navigation.tabs

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

extra:
  cdn_base_url: "https://bcit-ltc-cdn-h3aafscucgd4dvd3.z03.azurefd.net"
  cdn_namespace: "bcit-ltc"
  cdn_app: "infrastructure-documentation"

hooks:
  - hooks/cdn_rewrite.py

markdown_extensions:
  - abbr
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home:
      - index.md
      - services-systems.md
  - For Developers:
      - for-developers/index.md
      - for-developers/getting-started.md
      - for-developers/development-workflow.md
      - for-developers/routes-endpoints.md
      - for-developers/secrets.md
      - for-developers/semantic-versioning.md
      - for-developers/continuous-deployment-overview.md
      - Deployment details:
          - for-developers/developing-deployment-packages.md
          - for-developers/continuous-deployment-details.md
    # - for-developers/pipeline-initial-run.md
  - Additional Details:
      - Container Development:
          - container-development/index.md
          - container-development/kubernetes.md
          - container-development/deployments-releases.md
          - container-development/pipeline-overview.md
          - Deployment config details: container-development/deployment-packages.md
      - Infrastructure:
          - infrastructure-details/index.md
          - infrastructure-details/node-details.md
          - infrastructure-details/kubernetes-details.md
          # - infrastructure-details/pipeline-details.md
          - infrastructure-details/configuration.md
          - infrastructure-details/initializing-latest-stable.md
          - infrastructure-details/developing-infrastructure.md
      - Announcements:
          - announcements/index.md
          - announcements/gitlab-restructuring.md
          - announcements/deployment-package-changes.md
