apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qcon-api-ingress
spec:
  tls:
    - hosts:
        - latest.dev.ltc.bcit.ca
      secretName: star-dev-ltc-bcit-ca
  rules:
    - host: latest.dev.ltc.bcit.ca
      http:
        paths:
          - path: /qcon-api
            pathType: Prefix
            backend:
              service:
                name: qcon-api
                port:
                  number: 8000