apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qcon-api

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - configmap.yaml

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      
secretGenerator:
  - type: kubernetes.io/tls
    name: star-dev-ltc-bcit-ca
    files:
      - tls.crt
      - tls.key

generatorOptions:
  disableNameSuffixHash: true