# Build image with Kaniko and push to project registry
.build_image:
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    IMAGE_LABELS: >
      --label org.opencontainers.image.source=$CI_PROJECT_URL
      --label git_tag=$GIT_TAG
      --label org.opencontainers.image.version=$IMAGE_TAG
      --label org.opencontainers.image.revision=$BUILD_HASH
      --label build_short_sha=$BUILD_SHORT_SHA
    KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"
    KANIKO_SNAPSHOT_ARGS: "--snapshotMode=redo"
  script:
    - | 
      echo -e "Building and shipping image to $CI_REGISTRY_IMAGE"

      IMAGE_TITLE=$(echo $CI_PROJECT_TITLE | tr " " "_")

      # \$BUILD_DATE will be slightly different from \$CI_PIPELINE_CREATED_AT
      BUILD_DATE="$(date '+%FT%T%z' | sed -E -n 's/(\+[0-9]{2})([0-9]{2})$/\1:\2/p')"   #rfc 3339 date

      # Inject build envs into image
      echo -e "\nGIT_TAG=$GIT_TAG\
      \nIMAGE_TAG=$IMAGE_TAG\
      \nBUILD_HASH=$BUILD_HASH\
      \nBUILD_SHORT_SHA=$BUILD_SHORT_SHA\
      \nIMAGE_TITLE=$IMAGE_TITLE\
      \nBUILD_DATE=$BUILD_DATE\
      \n" \
        >> .env

      IMAGE_LABELS="$IMAGE_LABELS \
        --label org.opencontainers.image.title=$IMAGE_TITLE \
        --label org.opencontainers.image.created=$BUILD_DATE"

      echo -e " \
        \nImage Labels being applied: \
        \n  org.opencontainers.image.source=$CI_PROJECT_URL \
        \n  git_tag=$GIT_TAG \
        \n  org.opencontainers.image.version=$IMAGE_TAG \
        \n  org.opencontainers.image.revision=$BUILD_HASH \
        \n  build_short_sha=$BUILD_SHORT_SHA \
        \n  org.opencontainers.image.title=$IMAGE_TITLE \
        \n  org.opencontainers.image.created=$BUILD_DATE \
        \n"
        
      ADDITIONALTAGLIST="$ADDITIONALTAGLIST $IMAGE_TAG"

      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then ADDITIONALTAGLIST="$ADDITIONALTAGLIST latest"; fi

      if [[ "$CI_COMMIT_TAG" ]]; then
        ADDITIONALTAGLIST="$ADDITIONALTAGLIST $GIT_TAG stable"; fi

      if [[ -n "$ADDITIONALTAGLIST" ]]; then 
        for TAG in $ADDITIONALTAGLIST; do 
          FORMATTEDTAGLIST="${FORMATTEDTAGLIST} --tag $CI_REGISTRY_IMAGE:$TAG "; 
        done;
      fi
      
      # Reformat Docker tags to kaniko's --destination argument:
      FORMATTEDTAGLIST=$(echo "${FORMATTEDTAGLIST}" | sed s/\-\-tag/\-\-destination/g) 

      mkdir -p /kaniko/.docker
 
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" \
        > /kaniko/.docker/config.json
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile $KANIKO_CACHE_ARGS $KANIKO_SNAPSHOT_ARGS $FORMATTEDTAGLIST $IMAGE_LABELS